line-length = 200
select = ["E", "F", "W", "I", "N", "UP", "B", "C90", "A", "C4", "T20", "SIM", "TID", "ARG", "DTZ", "PIE", "Q", "RET", "RUF"]
ignore = ["E501"]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
]

target-version = "py39"
