line-length = 170
target-version = "py38"

[lint]
select = ["E", "F", "I", "N", "UP", "B", "C4", "SIM", "RUF"]
ignore = ["E501"]  # Line length handled by formatter

[format]
quote-style = "double"
indent-style = "space"